## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
#1
import numpy as np
x = np.zeros((10,10))
x[0,:] = 1
x[-1,:] = 1
x[:,0] = 1
x[:,-1] = 1
x
# For column : numpy_Array_name[  : ,column] 
# For row : numpy_Array_name[ row, :  ]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [3]:
#2
x = np.arange(5)
x = np.tile(x, (5, 1))
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [4]:
#3
x = np.zeros((8,8))
x[1::2, ::2] = 1  # start from second row
x[::2, 1::2] = 1  # start from second column
x


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [5]:
#4
x = np.array([1,2,3,4,5,6,7,8,9])
x[x%2==1]


array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [6]:
#5
mean, std = 4,3 
x = np.random.normal(mean , std, (5,5))

normalized_x = (x - mean ) / std # z
normalized_x

array([[ 1.70261154, -1.61502976,  0.1998233 , -0.12069183,  1.56991089],
       [-1.59558555, -0.39582276, -0.02662991, -0.52946717, -0.97171232],
       [ 0.9686414 , -0.41407141, -2.12248185, -0.78902717,  1.21253841],
       [ 0.17101574, -0.72846383, -1.00698536, -0.7803231 ,  0.7246867 ],
       [ 0.50874825,  1.42177055, -0.68038916,  0.20426915,  1.47129893]])

6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [7]:
#6
randomMat = np.random.rand(10, 2)

X = randomMat[:, 0]
Y = randomMat[:, 1]

R = np.sqrt(X**2 + Y**2) 
T = np.arctan2(Y, X)       

print(X, Y)
print(R)
print(T)

[0.47752705 0.10022984 0.68380055 0.13154449 0.36610663 0.61277252
 0.29949173 0.58819488 0.8233063  0.07221328] [0.58321503 0.89518942 0.30781532 0.53486193 0.02434206 0.2930291
 0.18443924 0.33061826 0.73971348 0.03769505]
[0.75377175 0.90078306 0.74988897 0.55080055 0.36691498 0.67923208
 0.35172877 0.67474562 1.10680138 0.08145965]
[0.8847063  1.45929576 0.4229817  1.32964151 0.06639128 0.44605771
 0.55198584 0.51207769 0.73196746 0.48108921]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [8]:
#7 
# x = np.zeros(17)
# count = 0
# for i in range(5): 
#     x[count] = i+1
#     count+=4
# x

arr = np.array([1, 2, 3, 4, 5])
x = np.zeros(17)
x[::4] = arr
x

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [9]:
#8
0 * np.nan
# nan

np.nan == np.nan
# False

np.inf > np.nan
# False

np.nan - np.nan
# nan

np.nan in set([np.nan])
# True

0.3 == 3 * 0.1 
# False

print(3 * 0.1)

0.30000000000000004


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [10]:
#9
np.array(0) / np.array(0)
# nan

np.array(0) // np.array(0)
# 0

np.array([np.nan]).astype(int).astype(float)
# array([-9.22337204e+18])
# The process of converting np.nan to an integer first yields an unexpected value due to the fact that NaN cannot be represented as an integer. 
# When you cast NaN to int, it typically results in the minimum integer value, such as -9223372036854775808 (on a 64-bit system). 
# After converting this back to float, you get -9.22337204e+18 in scientific notation.

C:\Users\aaron\AppData\Local\Temp\ipykernel_35280\581054890.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\aaron\AppData\Local\Temp\ipykernel_35280\581054890.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\aaron\AppData\Local\Temp\ipykernel_35280\581054890.py:8: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [13]:
x = np.array(([134, 28, 21, 4, 5,2], [13, 27,2,0,0,0],[7,1,21,0,0,0],
             [11,0,0,16,0,1],[2,0,0,0,11,2],[5,0,0,0,0,8]))
print(x)

[[134  28  21   4   5   2]
 [ 13  27   2   0   0   0]
 [  7   1  21   0   0   0]
 [ 11   0   0  16   0   1]
 [  2   0   0   0  11   2]
 [  5   0   0   0   0   8]]
